version: '2.1'

volumes:
  dbdata: {}

services:
  app:
    build: .
    image: fuco1/entity-repository
    command: php -S 0.0.0.0:8080 -t www www/index.php
    working_dir: ${PWD}
    ports:
      - 8080:8080
    volumes:
      - .:${PWD}
  mysql:
    image: mysql:5.7
    env_file: .env
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - dbdata:/var/lib/mysql
